options:
  formatter: stylish
  merge-default-rules: false
files:
  include: 'client/**/*.s+(a|c)ss'
  ignore:
    - 'client/styles/old_styles/**.*'
    - 'client/styles/fonts/**.*'
cache-config: true
rules:
  # Extends
  extends-before-mixins:
    - 2
    - include: true
  extends-before-declarations:
    - 2
    - include: true
  placeholder-in-extend:
    - 2
    - include: true

  # Mixins
  mixins-before-declarations:
    - 2
    - include: true

  # Line Spacing
  one-declaration-per-line:
    - 2
    - include: true
  empty-line-between-blocks:
    - 2
    - include: true
    - allow-single-line-rulesets: false
  single-line-per-selector:
    - 2
    - include: true

  # Disallows
  no-attribute-selectors: 0
  no-color-hex: 2
  no-color-keywords:
    - 2
    - include: true
  no-color-literals:
    - 2
    - allow-map-identifiers: true
      allow-rgba: true
      allow-variable-identifiers: true
  no-combinators: 0
  no-css-comments: 2
  no-debug: 2
  no-disallowed-properties: 0
  no-duplicate-properties:
    - 2
    - include: true
  no-empty-rulesets:
    - 2
    - include: true
  no-extends: 0
  no-ids:
    - 2
    - include: true
  no-important:
    - 2
    - include: true
  no-invalid-hex:
    - 2
    - include: true
  no-mergeable-selectors:
    - 2
    - include: true
  no-misspelled-properties:
    - 2
    - extra-properties:
      - 'gap'
      - 'scroll-margin'
      - 'scroll-margin-top'
      - 'scroll-margin-right'
      - 'scroll-margin-bottom'
      - 'scroll-margin-left'
      - 'scroll-padding'
      - 'scroll-padding-top'
      - 'scroll-padding-right'
      - 'scroll-padding-bottom'
      - 'scroll-padding-left'
  no-qualifying-elements:
    - 2
    - allow-element-with-id: false
      allow-element-with-attribute: false
      allow-element-with-class: false
  no-trailing-whitespace:
    - 2
    - include: true
  no-trailing-zero:
    - 2
    - include: true
  no-transition-all:
    - 2
    - include: true
  no-universal-selectors: 0
  no-url-domains:
    - 1
    - include: true
  no-url-protocols: 1
  no-vendor-prefixes:
    - 2
    - additional-identifiers: []
      excluded-identifiers: []
      ignore-non-standard: false
  no-warn:
    - 2
    - include: true
  property-units: 2

  # Nesting
  declarations-before-nesting:
    - 2
    - include: true
  force-attribute-nesting:
    - 2
    - include: true
  force-element-nesting:
    - 2
    - include: true
  force-pseudo-nesting:
    - 2
    - include: true

  # Name Formats
  class-name-format:
    - 2
    - allow-leading-underscore: false
      convention: 'hyphenatedlowercase'
  function-name-format:
    - 2
    - allow-leading-underscore: false
      convention: 'hyphenatedlowercase'
  id-name-format:
    - 2
    - allow-leading-underscore: false
      convention: 'hyphenatedlowercase'
  mixin-name-format:
    - 2
    - allow-leading-underscore: false
      convention: 'hyphenatedlowercase'
  placeholder-name-format:
    - 2
    - allow-leading-underscore: false
      convention: 'hyphenatedlowercase'
  variable-name-format:
    - 2
    - allow-leading-underscore: false
      convention: 'hyphenatedlowercase'

  # Style Guide
  attribute-quotes:
    - 2
    - include: true
  bem-depth: 0
  border-zero:
    - 2
    - convention: 'none'
  brace-style:
    - 2
    - style: '1tbs'
    - allow-single-line: false
  clean-import-paths:
    - 2
    - leading-underscore: false
      filename-extension: false
  empty-args:
    - 1
    - include: true
  hex-length:
    - 2
    - style: long
  hex-notation:
    - 2
    - style: lowercase
  indentation:
    - 2
    - size: 2
  leading-zero:
    - 2
    - include: true
  max-line-length:
    - 2
    - length: 120
  max-file-line-count:
    - 2
    - length: 300
  nesting-depth:
    - 2
    - max-depth: 2
  pseudo-element:
    - 2
    - include: true
  quotes:
    - 2
    - style: double
  shorthand-values:
    - 2
    - allowed-shorthands:
        - 1
        - 2
        - 3
  url-quotes: 2
  variable-for-property:
    - 2
    - allow-map-get: true
      properties:
        - 'font-family'
  zero-unit:
    - 2
    - include: false

  # Inner Spacing
  space-after-comma:
    - 2
    - include: true
  space-before-colon:
    - 2
    - include: false
  space-after-colon:
    - 2
    - include: true
  space-before-brace:
    - 2
    - include: true
  space-before-bang:
    - 2
    - include: true
  space-after-bang:
    - 2
    - include: false
  space-between-parens:
    - 2
    - include: false
  space-around-operator:
    - 2
    - include: true

  # Final Items
  trailing-semicolon:
    - 2
    - include: true
  final-newline:
    - 2
    - include: true

  # Property sort order
  property-sort-order:
    - 2
    - order:
      # Positioning
      - content
      - position
      - inset
      - top
      - right
      - bottom
      - left
      - z-index

      # Block model
      - display
      # Flex
      - flex
      - flex-grow
      - flex-shrink
      - flex-basis
      - flex-flow
      - flex-direction
      - flex-wrap
      # Grid
      - grid
      - grid-template
      - grid-template-areas
      - grid-template-columns
      - grid-template-rows
      - grid-auto-flow
      - grid-auto-rows
      - grid-auto-columns
      - grid-area
      - grid-column
      - grid-column-start
      - grid-column-end
      - grid-row
      - grid-row-start
      - grid-row-end
      - grid-gap
      - grid-column-gap
      - grid-row-gap
      # Flex and Grid
      - gap
      - column-gap
      - row-gap
      - place-content
      - justify-content
      - align-content
      - place-items
      - justify-items
      - align-items
      - place-self
      - justify-self
      - align-self
      - order
      - float
      - clear
      - box-sizing
      - width
      - min-width
      - max-width
      - height
      - min-height
      - max-height
      - margin
      - margin-top
      - margin-right
      - margin-bottom
      - margin-left
      - padding
      - padding-top
      - padding-right
      - padding-bottom
      - padding-left
      - overflow
      - overflow-x
      - overflow-y

      # Typography
      - list-style
      - list-style-position
      - list-style-type
      - list-style-image
      - border-collapse
      - border-spacing
      - table-layout
      - empty-cells
      - caption-side
      - font
      - font-style
      - font-variant
      - font-weight
      - font-size
      - line-height
      - font-family
      - vertical-align
      - text-align
      - direction
      - color
      - text-transform
      - text-decoration
      - font-size-adjust
      - font-stretch
      - font-effect
      - font-emphasize
      - font-emphasize-position
      - font-emphasize-style
      - font-smooth
      - text-align-last
      - letter-spacing
      - word-spacing
      - white-space
      - text-emphasis
      - text-emphasis-color
      - text-emphasis-style
      - text-emphasis-position
      - text-indent
      - text-justify
      - text-outline
      - text-wrap
      - text-overflow
      - text-overflow-ellipsis
      - text-overflow-mode
      - text-orientation
      - word-wrap
      - word-break
      - tab-size
      - hyphens
      - unicode-bidi
      - columns
      - column-count
      - column-fill
      - column-gap
      - column-rule
      - column-rule-color
      - column-rule-style
      - column-rule-width
      - column-span
      - column-width
      - text-shadow
      - page-break-after
      - page-break-before
      - page-break-inside

      # Decor
      - background
      - background-color
      - background-image
      - linear-gradient
      - background-repeat
      - background-position
      - background-position-x
      - background-position-y
      - background-size
      - background-clip
      - background-origin
      - background-attachment
      - box-decoration-break
      - background-blend-mode
      - border
      - border-width
      - border-style
      - border-color
      - border-top
      - border-top-width
      - border-top-style
      - border-top-color
      - border-right
      - border-right-width
      - border-right-style
      - border-right-color
      - border-bottom
      - border-bottom-width
      - border-bottom-style
      - border-bottom-color
      - border-left
      - border-left-width
      - border-left-style
      - border-left-color
      - border-radius
      - border-top-left-radius
      - border-top-right-radius
      - border-bottom-right-radius
      - border-bottom-left-radius
      - border-image
      - border-image-source
      - border-image-slice
      - border-image-width
      - border-image-outset
      - border-image-repeat
      - outline
      - outline-width
      - outline-style
      - outline-color
      - outline-offset
      - box-shadow
      - transform
      - transform-origin
      - backface-visibility
      - perspective
      - perspective-origin
      - transform-style
      - visibility
      - cursor
      - opacity
      - filter

      # Animation
      - transition
      - transition-delay
      - transition-timing-function
      - transition-duration
      - transition-property
      - animation
      - animation-name
      - animation-duration
      - animation-play-state
      - animation-timing-function
      - animation-delay
      - animation-iteration-count
      - animation-direction

      # Other
      - object-fit
      - quotes
      - counter-reset
      - counter-increment
      - resize
      - user-select
      - nav-index
      - nav-up
      - nav-right
      - nav-down
      - nav-left
      - pointer-events
      - will-change
      - clip
      - clip-path
      - zoom
      - scroll-behavior
      - scroll-margin
      - scroll-margin-top
      - scroll-margin-right
      - scroll-margin-bottom
      - scroll-margin-left
      - scroll-padding
      - scroll-padding-top
      - scroll-padding-right
      - scroll-padding-bottom
      - scroll-padding-left
      - text-rendering
      - text-size-adjust
